config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :todo_lists
  namespace :admin do
    resources :users
    resources :announcements
    resources :services
    resources :notifications

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if todo_list.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', todo_list, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if todo_list.persisted? %>
      <%= link_to "Cancel", todo_list, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", todo_lists_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Edit Todo_list</h1>

<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Todo_lists</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_todo_list_path, class: 'btn btn-primary' do %>
    Add New Todo list
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Title</th>
            <th>Description</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @todo_lists.each do |todo_list| %>
        <%= content_tag :tr, id: dom_id(todo_list), class: dom_class(todo_list) do %>
          

                      <td><%= todo_list.title %></td>
                      <td><%= todo_list.description %></td>
          
          
            <td><%= link_to 'Show', todo_list %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/todo_lists/new.html.erb
<h1>New todo_list</h1>

<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/show.html.erb
<div class="page-header">
  <%= link_to todo_lists_path, class: 'btn btn-default' do %>
    All Todo_lists
  <% end %>
  <%= link_to edit_todo_list_path(@todo_list), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show todo_list</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @todo_list.title %></dd>

  <dt>Description:</dt>
  <dd><%= @todo_list.description %></dd>

</dl>